data:
  uniprot_id: "P00533"
  bioactivity_measures: [
    "Kd",
    "Ki"
  ]
  bioactivity_threshold: 1000
  bioactive_smiles_save_path: "../data/preprocessed/uniprot-id/P00533/chembl_bioactives"
  cache_dir: "../data/cache/P00533/chembl/"
  log_path: "../var/log/P00533/chembl/data_ingestion.log"